/** Unique Workout Plan exercises. One gym-wide demo video per exerciseKey. */

export type WorkoutPlanExercise = {
  exerciseKey: string;
  name: string;
};

export const WORKOUT_PLAN_EXERCISES: WorkoutPlanExercise[] = [
  { exerciseKey: "arnold_press", name: "Arnold Press" },
  { exerciseKey: "assisted_pull_up", name: "Assisted Pull-Up" },
  { exerciseKey: "back_squat", name: "Back Squat" },
  { exerciseKey: "barbell_bench_press", name: "Barbell Bench Press" },
  { exerciseKey: "barbell_row", name: "Barbell Row" },
  { exerciseKey: "bulgarian_split_squat", name: "Bulgarian Split Squat" },
  { exerciseKey: "cable_crunch", name: "Cable Crunch" },
  { exerciseKey: "cable_curl", name: "Cable Curl" },
  { exerciseKey: "cable_fly", name: "Cable Fly" },
  { exerciseKey: "cable_lateral_raise", name: "Cable Lateral Raise" },
  { exerciseKey: "chest_supported_row", name: "Chest-Supported Row" },
  { exerciseKey: "dead_bug", name: "Dead Bug" },
  { exerciseKey: "deadlift_or_trap_bar", name: "Deadlift/Trap-Bar Deadlift" },
  { exerciseKey: "dips_assisted", name: "Dips/Assisted Dips" },
  { exerciseKey: "dumbbell_curl", name: "Dumbbell Curl" },
  { exerciseKey: "dumbbell_lateral_raise", name: "Dumbbell Lateral Raise" },
  { exerciseKey: "dumbbell_rdl", name: "Dumbbell Romanian Deadlift" },
  { exerciseKey: "dumbbell_row", name: "Dumbbell Row" },
  { exerciseKey: "dumbbell_shoulder_press", name: "Dumbbell Shoulder Press" },
  { exerciseKey: "ez_bar_curl", name: "EZ-Bar Curl" },
  { exerciseKey: "face_pull", name: "Face Pull" },
  { exerciseKey: "front_squat", name: "Front Squat" },
  { exerciseKey: "goblet_squat", name: "Goblet Squat" },
  { exerciseKey: "hack_squat", name: "Hack Squat" },
  { exerciseKey: "hammer_curl", name: "Hammer Curl" },
  { exerciseKey: "hanging_knee_raise", name: "Hanging Knee Raise" },
  { exerciseKey: "hanging_leg_raise", name: "Hanging Leg Raise" },
  { exerciseKey: "hip_thrust", name: "Hip Thrust" },
  { exerciseKey: "incline_barbell_press", name: "Incline Barbell Press" },
  { exerciseKey: "incline_bench_press", name: "Incline Bench Press" },
  { exerciseKey: "incline_dumbbell_press", name: "Incline Dumbbell Press" },
  { exerciseKey: "lat_pulldown", name: "Lat Pulldown" },
  { exerciseKey: "leg_curl", name: "Leg Curl" },
  { exerciseKey: "leg_extension", name: "Leg Extension" },
  { exerciseKey: "leg_press", name: "Leg Press" },
  { exerciseKey: "machine_chest_press", name: "Machine Chest Press" },
  { exerciseKey: "neutral_grip_pulldown", name: "Neutral-Grip Pulldown" },
  { exerciseKey: "one_arm_dumbbell_row", name: "One-Arm Dumbbell Row" },
  { exerciseKey: "overhead_cable_extension", name: "Overhead Cable Extension" },
  { exerciseKey: "overhead_press", name: "Overhead Press" },
  { exerciseKey: "overhead_triceps_extension", name: "Overhead Triceps Extension" },
  { exerciseKey: "pec_deck", name: "Pec Deck" },
  { exerciseKey: "plank", name: "Plank" },
  { exerciseKey: "preacher_curl", name: "Preacher Curl" },
  { exerciseKey: "pull_up_or_lat_pulldown", name: "Pull-Up/Lat Pulldown" },
  { exerciseKey: "rear_delt_fly", name: "Rear Delt Fly" },
  { exerciseKey: "romanian_deadlift", name: "Romanian Deadlift" },
  { exerciseKey: "rope_triceps_pushdown", name: "Rope Triceps Pushdown" },
  { exerciseKey: "seated_cable_row", name: "Seated Cable Row" },
  { exerciseKey: "seated_calf_raise", name: "Seated Calf Raise" },
  { exerciseKey: "seated_leg_curl", name: "Seated Leg Curl" },
  { exerciseKey: "seated_shoulder_press", name: "Seated Shoulder Press" },
  { exerciseKey: "split_squat", name: "Split Squat" },
  { exerciseKey: "standing_calf_raise", name: "Standing Calf Raise" },
  { exerciseKey: "straight_arm_pulldown", name: "Straight-Arm Pulldown" },
  { exerciseKey: "weighted_pull_up", name: "Weighted Pull-Up" },
];

export const MAX_WORKOUT_PLAN_VIDEO_BYTES = 50 * 1024 * 1024;
